apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops-demo-webapp
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/salman574/gitops-demo-webapp

